### ISSUE TITLE
Need Access to Create Repo

### ISSUE THREAD

**Issue by brgibson** [edmunds/edmunds.github.io#1]
@edmunds/core would someone be able to create the repo edmunds.github.io or update my status to "Owner" so that I can create this repo?

**Comment by ksader-edmunds** [comment]
Do you want a new repo created or a new TLD?

**Comment by brgibson** [comment]
@ksader-edmunds I think just a new repo.

**Comment by brgibson** [comment]
edmunds.github.io/blog is already available, but in order for the DNS routing for technology.edmunds.com, I will need to create the edmunds.github.io repo instead.

**Comment by ksader-edmunds** [comment]
Done https://github.com/edmunds/edmunds.github.io

**Comment by brgibson** [comment]
Thanks

**Comment by brgibson** [comment]
@ksader-edmunds I don't seem to have permissions to commit the new repo

**Comment by l0s** [comment]
All, can we delete the new `edmunds.github.io` repo and just rename the `blog` repo to `edmunds.github.io`? We are limited in the number of repositories we can create.

**Comment by brgibson** [comment]
That is fine with me.  Or, once I can commit to edmunds.github.io, we can delete the blog repo.  This also doesn't need to be a private repo (if we have a limited number of those).

**Comment by l0s** [comment]
Ok, that's done. Sorry, you're right, our limit is only on the number of private repositories. However, this way we retain your commit history.

**Comment by l0s** [comment]
@brgibson, note I had to copy your commits to the branch `master` in order for the site to show up at: https://edmunds.github.io/ .

**Comment by brgibson** [comment]
@l0s Perfect.  That's correct for the github.io root version.  Thanks!
